# SPDX-License-Identifier: GPL-2.0
#
# ovpn -- OpenVPN data channel offload in kernel space
#
# Copyright (C) 2020-2022 OpenVPN, Inc.
#
# Author:	Antonio Quartulli <antonio@openvpn.net>

obj-$(CONFIG_OVPN) += ovpn.o
ovpn-y += main.o
ovpn-y += bind.o
ovpn-y += crypto.o
ovpn-y += io.o
ovpn-y += peer.o
ovpn-y += sock.o
ovpn-y += stats.o
ovpn-y += netlink.o
ovpn-y += crypto_aead.o
ovpn-y += pktid.o
ovpn-y += tcp.o
ovpn-y += udp.o
