# SPDX-License-Identifier: GPL-2.0
#
# ovpn-dco -- OpenVPN data channel offload in kernel space
#
# Copyright (C) 2020 OpenVPN, Inc.
#
# Author:	Antonio Quartulli <antonio@openvpn.net>

obj-$(CONFIG_OVPN_DCO) += ovpn-dco.o
ovpn-dco-y += main.o
ovpn-dco-y += addr.o
ovpn-dco-y += bind.o
ovpn-dco-y += crypto.o
ovpn-dco-y += ovpn.o
ovpn-dco-y += peer.o
ovpn-dco-y += sock.o
ovpn-dco-y += stats.o
ovpn-dco-y += netlink.o
ovpn-dco-y += aead.o
ovpn-dco-y += pktid.o
