---
name: virtme-ng build

"on":
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"

permissions:
  contents: read

jobs:
  vng-tests:
    uses: mandelbitdev/kmod-ci/.github/workflows/out-of-tree-vng.yml@main
    with:
      cache-prefix: ovpn-dco
      guest-script: ci/run-build.sh
      distros: >-
        ["debian-12", "debian-13",
        "ubuntu-22.04", "ubuntu-24.04", "ubuntu-26.04",
        "rhel-8", "rhel-9", "rhel-10"]
    secrets:
      RHEL_ORG_ID: ${{ secrets.RHEL_ORG_ID }}
      RHEL_ACTIVATION_KEY: ${{ secrets.RHEL_ACTIVATION_KEY }}
